# Configuracao do Oracle - FIAP
# Tambem pode sobrescrever com variaveis de ambiente: DB_URL, DB_USER, DB_PASSWORD
db.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
db.user=rm572019
db.password=070108
